---

- hosts: all
  become: true
  tasks:
  - name: install apache2,php on RHEL 8 
    package: 
      name:
       - httpd
       - php
    when: ansible_distribution in ['Rocky', 'Fedora'] and ansible_distribution_major_version == "8"

  - name: install apache2 on RHEL 7
    package: 
      name: httpd
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
