---

- hosts: all
  become: true
  tasks:
  - name: install apache2 on RHEL 8 
    dnf: 
      name: httpd
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8"

  - name: install apache2 on RHEL 7
    yum: 
      name: httpd
    when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
